package com.elp.dao;

import com.yimeicloud.community.api.model.Permission;

public interface PermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permissions
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permissions
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int insert(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permissions
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int insertSelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permissions
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	Permission selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permissions
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int updateByPrimaryKeySelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permissions
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int updateByPrimaryKey(Permission record);
}