package com.elp.dao;

import com.yimeicloud.community.api.model.Role;

public interface RoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int insert(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int insertSelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	Role selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int updateByPrimaryKeySelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int updateByPrimaryKey(Role record);
}