package com.elp.dao;

import com.yimeicloud.community.api.model.RolePermissionKey;
import com.yimeicloud.community.api.model.RolePermission;

public interface RolePermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_permissions
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int deleteByPrimaryKey(RolePermissionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_permissions
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int insert(RolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_permissions
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int insertSelective(RolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_permissions
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	RolePermission selectByPrimaryKey(RolePermissionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_permissions
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int updateByPrimaryKeySelective(RolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_permissions
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int updateByPrimaryKey(RolePermission record);
}