package com.elp.dao;

import com.yimeicloud.community.api.model.ServiceNotifyLog;

public interface ServiceNotifyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_notify_log
     *
     * @mbggenerated Mon Aug 15 17:51:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_notify_log
     *
     * @mbggenerated Mon Aug 15 17:51:52 CST 2016
     */
    int insert(ServiceNotifyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_notify_log
     *
     * @mbggenerated Mon Aug 15 17:51:52 CST 2016
     */
    int insertSelective(ServiceNotifyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_notify_log
     *
     * @mbggenerated Mon Aug 15 17:51:52 CST 2016
     */
    ServiceNotifyLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_notify_log
     *
     * @mbggenerated Mon Aug 15 17:51:52 CST 2016
     */
    int updateByPrimaryKeySelective(ServiceNotifyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_notify_log
     *
     * @mbggenerated Mon Aug 15 17:51:52 CST 2016
     */
    int updateByPrimaryKey(ServiceNotifyLog record);
}