package com.elp.dao;

import com.yimeicloud.community.api.model.UserRoleKey;
import com.yimeicloud.community.api.model.UserRole;

public interface UserRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_roles
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int deleteByPrimaryKey(UserRoleKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_roles
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int insert(UserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_roles
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int insertSelective(UserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_roles
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	UserRole selectByPrimaryKey(UserRoleKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_roles
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int updateByPrimaryKeySelective(UserRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_roles
	 * @mbggenerated  Wed Jul 27 15:46:49 CST 2016
	 */
	int updateByPrimaryKey(UserRole record);
}