package com.elp.model;

import java.util.Date;

public class ReserveUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_user_info.id
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_user_info.theme
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_user_info.username
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_user_info.portrait
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    private String portrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_user_info.status
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_user_info.create_date
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_user_info.update_date
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_user_info.id
     *
     * @return the value of reserve_user_info.id
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_user_info.id
     *
     * @param id the value for reserve_user_info.id
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_user_info.theme
     *
     * @return the value of reserve_user_info.theme
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_user_info.theme
     *
     * @param theme the value for reserve_user_info.theme
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_user_info.username
     *
     * @return the value of reserve_user_info.username
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_user_info.username
     *
     * @param username the value for reserve_user_info.username
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_user_info.portrait
     *
     * @return the value of reserve_user_info.portrait
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_user_info.portrait
     *
     * @param portrait the value for reserve_user_info.portrait
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait == null ? null : portrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_user_info.status
     *
     * @return the value of reserve_user_info.status
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_user_info.status
     *
     * @param status the value for reserve_user_info.status
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_user_info.create_date
     *
     * @return the value of reserve_user_info.create_date
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_user_info.create_date
     *
     * @param createDate the value for reserve_user_info.create_date
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_user_info.update_date
     *
     * @return the value of reserve_user_info.update_date
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_user_info.update_date
     *
     * @param updateDate the value for reserve_user_info.update_date
     *
     * @mbggenerated Fri Aug 19 11:53:34 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}